import type { Metadata } from "next";

import "./globals.css";

import { Frontpage} from "./FrontPage";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className="antialiased"
      >
        <Frontpage>
          {children}
        </Frontpage>
        
      </body>
    </html>
  );
}
